spring:
  config:
    activate:
      on-profile: dev
  rabbitmq:
    host: localhost
    port: 5672
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 5
          multiplier: 1.5
        default-requeue-rejected: false
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        multiplier: 1.5
    username: guest
    password: guest

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
    database: mysql
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

logging:
  file:
    path: ${user.dir}/logs/${spring.application.name}

server:
  port: 8081

eureka:
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/
  gateway: http://localhost:8085

jwt:
  secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

api:
  books-users: http://localhost:8061
  auth: http://localhost:8050
