spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://133.186.241.167:3306/be6_yes255_coupon
    username: be6_yes255
    password: ${YES25_5_MYSQL_PASSWORD}
    dbcp2:
      max-total: 10
      max-idle: 5
      min-idle: 2
      max-wait-millis: 10000

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
    database: mysql
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  data:
    redis:
      host: 133.186.241.167
      port: 6379
      database: 34
      password: ${YES25_5_REDIS_PASSWORD}

  application:
    name: coupon-server

logging:
  file:
    path: ${user.home}/logs/${spring.application.name}
  level:
    org.springframework.amqp.rabbit.listener: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace

server:
  port: 8080

eureka:
  gateway: http://133.186.153.195:8085
  instance:
    hostname: ${EUREKA_SERVER_HOSTNAME}
  client:
    enabled: true
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOSTNAME}:${EUREKA_SERVER_PORT}/eureka/

springdoc:
  api-docs:
    path: /coupons/v3/api-docs
  swagger-ui:
    path: /coupons/swagger-ui.html

jwt:
  secret: ${JWT_SECRET}

api:
  books-users: ${BOOK_USER_SERVER}
  coupon: ${COUPON_SERVER}
