spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://133.186.241.167:3306/be6_yes255_coupon
    username: be6_yes255
    password: ${YES25_5_MYSQL_PASSWORD}
    dbcp2:
      max-total: 10
      max-idle: 5
      min-idle: 2
      max-wait-millis: 10000

  data:
    redis:
      host: 133.186.241.167
      port: 6379
      database: 34
      password: ${YES25_5_REDIS_PASSWORD}

  application:
    name: coupon-server

logging:
  level:
    org.springframework.amqp.rabbit.listener: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace

springdoc:
  api-docs:
    path: /coupons/v3/api-docs
  swagger-ui:
    path: /coupons/swagger-ui.html

eureka:
  client:
    enabled: true
    fetchRegistry: true
    registerWithEureka: true
