spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://133.186.241.167:3306/be6_yes255_coupon
    username: be6_yes255
    password: ${YES25_5_MYSQL_PASSWORD}
  h2:
    console:
      enabled: false
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
    init:
      mode: always
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace
server:
  port: 8081

application:
  name: coupon-server

jwt:
  secret: ${JWT_SECRET:this-is-coupon-jwt-secret-key-i-am-hungry}
