spring:
  rabbitmq:
    host: 133.186.153.195
    port: 5672
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 5
          multiplier: 1.5
        default-requeue-rejected: false
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        multiplier: 1.5
    username: yes255
    password: yes255

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://133.186.241.167:3306/be6_yes255_coupon
    username: be6_yes255
    password: ${YES25_5_MYSQL_PASSWORD}
    dbcp2:
      max-total: 10
      max-idle: 5
      min-idle: 2
      max-wait-millis: 10000
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
    database: mysql
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  data:
    redis:
      host: 133.186.241.167
      port: 6379
      database: 34
      password: ${YES25_5_REDIS_PASSWORD}
  application:
    name: coupon-server
logging:
  file:
    path: ${user.home}/logs/${spring.application.name}
  level:
    org.springframework.amqp.rabbit.listener: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace
server:
  port: 8080
eureka:
  gateway: http://133.186.153.195:8085
  instance:
    hostname: ${EUREKA_SERVER_HOSTNAME}
  client:
    enabled: true
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOSTNAME}:${EUREKA_SERVER_PORT}/eureka/

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

# 배포 환경에서의 각 서버별 api 호출 코드를 환경변수에 등록합니다. 원격서버에도 등록되었는지 확인해주세요..
api:
  books-users: ${BOOK_USER_SERVER}
  coupon: ${COUPON_SERVER}
  auth : ${AUTH_SERVER}