spring:
  config:
    activate:
      on-profile: prod

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
    database: mysql
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true

logging:
  file:
    path: ${user.home}/logs/${spring.application.name}

server:
  port: 8080

eureka:
  instance:
    hostname: ${EUREKA_SERVER_HOSTNAME}
  serviceUrl:
    defaultZone: http://${EUREKA_SERVER_HOSTNAME}:${EUREKA_SERVER_PORT}/eureka/
  gateway: http://133.186.153.195:8085

jwt:
  secret: ${JWT_SECRET}

api:
  books-users: ${BOOK_USER_SERVER}
  coupon: ${COUPON_SERVER}
  auth: ${AUTH_SERVER}
